language: python
sudo: required
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get install python-numpy python-scipy python-matplotlib
install:
  - pip install .
# command to run tests
script: nosetests